server:
  port: 8080
  servlet:
    context-path: /lesson7
logging:
  level:
    com:
      buzas:
        lesson7: error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/for_patterns?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true